### ISSUE TITLE
Scale에 관한 질문

### ISSUE THREAD

**Issue by bmy4415** [leopard627/django-gunicorn-nginx-docker#11]
안녕하세요, medium 글을 보고 github repo까지 유입된 유저입니다.

`Dockerfile`, `supervisor-app-staging.conf` 를 보고 제가 이해한 바로는
하나의 docker container를 띄우고 그 container 내부에
supervisord / nginx / gunicorn / django(run by gunicorn) 프로세스가 모두 뜨는것으로 보입니다.

그렇다면 scaling을 하는데에 있어서 scale-out (container 추가 등 수평적 확장)은 힘든 구조이고 scale up(docker container가 뜨는 machine의 성능 확장)만 가능한 상태인게 맞나요?

감사합니다.

**Comment by leopard627** [comment]
이슈를 남겨주셔서 감사합니다! @bmy4415 

컨테이너환경(쿠버네틱스&도커스웜 etc etc)에서 스케일 업을 하게되면, 해당 컨테이너들을 머신 위에 무수히 많이 띄워놓기만 하면 되게 때문에 수평적 확장은 도커를 사용하고 있으니 그 자체로  충족하고 있다고 보시면 될것 같아요!!

다만 컨테이너 내부에 supervisor 그리고 nginx 가 함께 있으니 효율적이진 않습니다! 이녀석들을 외부로 빼면 좀더 좋은 퍼포먼스를 기대할수 있을거에요! 외부로 빼낸다면 굳이 supervisor를 사용할 필요는 없어질것 같네요! health-check은 따로 하면 되니까요!
